# Merge All Tables Together

## Data Input

In [1]:
import pandas as pd
import numpy as np

In [2]:
df_sleep = pd.read_csv('df_sleep_merge.csv')
df_sleep.head()

,id,day_in_study,timestamp,composition_score,revitalization_score,duration_score,deep_sleep_in_minutes,resting_heart_rate,restlessness,study_interval,...,sleep_end_timestamp,minutesasleep,minutesawake,timeinbed,study_interval_sleep,is_weekend_sleep,study_interval_comp,is_weekend_comp,temperature_samples,nightly_temperature
0,1,4,07:42:00,21.0,22.0,37.0,93.0,84.0,0.056404,2022,...,07:42:00,384,65,449,2022,False,2022.0,0.0,446.0,34.050056
1,1,7,10:04:30,18.0,21.0,42.0,86.0,82.0,0.035122,2022,...,10:04:30,467,51,518,2022,True,2022.0,1.0,400.0,33.854962
2,1,11,08:03:00,21.0,23.0,39.0,53.0,76.0,0.047014,2022,...,08:03:00,370,33,403,2022,False,2022.0,0.0,403.0,34.321625
3,1,12,08:06:00,19.0,22.0,39.0,49.0,77.0,0.051282,2022,...,08:06:00,398,42,440,2022,False,2022.0,0.0,440.0,34.857818
4,1,20,09:35:00,18.0,19.0,45.0,113.0,76.0,0.075188,2022,...,09:35:00,545,58,603,2022,False,2022.0,0.0,481.0,34.375042

In [3]:
df_sleep.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5078 entries, 0 to 5077
Data columns (total 36 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   id                               5078 non-null   int64
 1   day_in_study                     5078 non-null   int64
 2   timestamp                        5078 non-null   object
 3   composition_score                3566 non-null   float64
 4   revitalization_score             5078 non-null   float64
 5   duration_score                   3566 non-null   float64
 6   deep_sleep_in_minutes            5077 non-null   float64
 7   resting_heart_rate               5078 non-null   float64
 8   restlessness                     5078 non-null   float64
 9   study_interval                   5078 non-null   int64
 10  is_weekend                       5078 non-null   bool
 11  study_interval_resp              2532 non-null   float64
 12  is_weekend_resp                  2532 non-null   object
 13  full_sleep_breathing_rate_max    2532 non-null   float64
 14  full_sleep_breathing_rate_min    2532 non-null   float64
 15  full_sleep_breathing_rate_mean   2532 non-null   float64
 16  deep_sleep_breathing_rate_max    2532 non-null   float64
 17  deep_sleep_breathing_rate_min    2532 non-null   float64
 18  deep_sleep_breathing_rate_mean   2532 non-null   float64
 19  light_sleep_breathing_rate_max   2532 non-null   float64
 20  light_sleep_breathing_rate_min   2532 non-null   float64
 21  light_sleep_breathing_rate_mean  2532 non-null   float64
 22  rem_sleep_breathing_rate_max     2532 non-null   float64
 23  rem_sleep_breathing_rate_min     2532 non-null   float64
 24  rem_sleep_breathing_rate_mean    2532 non-null   float64
 25  sleep_start_timestamp            5078 non-null   object
 26  sleep_end_timestamp              5078 non-null   object
 27  minutesasleep                    5078 non-null   int64
 28  minutesawake                     5078 non-null   int64
 29  timeinbed                        5078 non-null   int64
 30  study_interval_sleep             5078 non-null   int64
 31  is_weekend_sleep                 5078 non-null   bool
 32  study_interval_comp              5006 non-null   float64
 33  is_weekend_comp                  5006 non-null   float64
 34  temperature_samples              5006 non-null   float64
 35  nightly_temperature              5006 non-null   float64
dtypes: bool(2), float64(23), int64(7), object(4)
memory usage: 1.3+ MB

In [4]:
df_hr = pd.read_csv('merged_Rashi.csv')
df_hr.head()

,id,study_interval,is_weekend_x,day_in_study,in_default_zone_3,in_default_zone_2,in_default_zone_1,below_default_zone_1,is_weekend_y,12am_bpm,...,4pm_hf,6pm_rmssd,6pm_lf,6pm_hf,8pm_rmssd,8pm_lf,8pm_hf,10pm_rmssd,10pm_lf,10pm_hf
0,1,2022,True,1,0.0,0.0,126.0,1036.0,True,75.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,2022,False,2,5.0,82.0,416.0,512.0,False,87.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1,2022,False,3,5.0,119.0,599.0,368.0,False,79.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1,2022,False,4,0.0,0.0,212.0,613.0,False,89.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1,2022,False,5,8.0,123.0,250.0,308.0,False,80.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
df_hr.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5450 entries, 0 to 5449
Data columns (total 58 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   id                    5450 non-null   int64
 1   study_interval        5450 non-null   int64
 2   is_weekend_x          5450 non-null   bool
 3   day_in_study          5450 non-null   int64
 4   in_default_zone_3     5450 non-null   float64
 5   in_default_zone_2     5450 non-null   float64
 6   in_default_zone_1     5450 non-null   float64
 7   below_default_zone_1  5450 non-null   float64
 8   is_weekend_y          5439 non-null   object
 9   12am_bpm              5115 non-null   float64
 10  2am_bpm               5209 non-null   float64
 11  4am_bpm               5254 non-null   float64
 12  6am_bpm               5283 non-null   float64
 13  8am_bpm               5257 non-null   float64
 14  10am_bpm              5250 non-null   float64
 15  12pm_bpm              5268 non-null   float64
 16  2pm_bpm               5226 non-null   float64
 17  4pm_bpm               5177 non-null   float64
 18  6pm_bpm               5160 non-null   float64
 19  8pm_bpm               5152 non-null   float64
 20  10pm_bpm              5149 non-null   float64
 21  is_weekend            4751 non-null   object
 22  12am_rmssd            3235 non-null   float64
 23  12am_lf               3235 non-null   float64
 24  12am_hf               3235 non-null   float64
 25  2am_rmssd             4320 non-null   float64
 26  2am_lf                4320 non-null   float64
 27  2am_hf                4320 non-null   float64
 28  4am_rmssd             4563 non-null   float64
 29  4am_lf                4563 non-null   float64
 30  4am_hf                4563 non-null   float64
 31  6am_rmssd             4310 non-null   float64
 32  6am_lf                4310 non-null   float64
 33  6am_hf                4310 non-null   float64
 34  8am_rmssd             3008 non-null   float64
 35  8am_lf                3008 non-null   float64
 36  8am_hf                3008 non-null   float64
 37  10am_rmssd            1153 non-null   float64
 38  10am_lf               1153 non-null   float64
 39  10am_hf               1153 non-null   float64
 40  12pm_rmssd            340 non-null    float64
 41  12pm_lf               340 non-null    float64
 42  12pm_hf               340 non-null    float64
 43  2pm_rmssd             136 non-null    float64
 44  2pm_lf                136 non-null    float64
 45  2pm_hf                136 non-null    float64
 46  4pm_rmssd             75 non-null     float64
 47  4pm_lf                75 non-null     float64
 48  4pm_hf                75 non-null     float64
 49  6pm_rmssd             62 non-null     float64
 50  6pm_lf                62 non-null     float64
 51  6pm_hf                62 non-null     float64
 52  8pm_rmssd             138 non-null    float64
 53  8pm_lf                138 non-null    float64
 54  8pm_hf                138 non-null    float64
 55  10pm_rmssd            1210 non-null   float64
 56  10pm_lf               1210 non-null   float64
 57  10pm_hf               1210 non-null   float64
dtypes: bool(1), float64(52), int64(3), object(2)
memory usage: 2.4+ MB

In [6]:
df_basic_hormones_glucose = pd.read_csv('merged_Grace.csv')
df_basic_hormones_glucose.head(5)

,id,study_interval,is_weekend,day_in_study,phase,lh,estrogen,pdg,flow_volume,flow_color,...,gender,ethnicity,education,sexually_active,self_report_menstrual_health_literacy,age_of_first_menarche,height2022,weight2022,height2024,weight2024
0,1,2022,True,1,Follicular,2.9,94.2,NaN,Not at all,Not at all,...,Woman,White,"Some university/ post-secondary, no degree",Yes,NaN,14,NaN,NaN,NaN,NaN
1,1,2022,False,2,Follicular,1.2,226.3,NaN,Not at all,Not at all,...,Woman,White,"Some university/ post-secondary, no degree",Yes,NaN,14,NaN,NaN,NaN,NaN
2,1,2022,False,3,Follicular,3.5,276.8,NaN,Not at all,Not at all,...,Woman,White,"Some university/ post-secondary, no degree",Yes,NaN,14,NaN,NaN,NaN,NaN
3,1,2022,False,4,Fertility,1.8,322.1,NaN,Not at all,Not at all,...,Woman,White,"Some university/ post-secondary, no degree",Yes,NaN,14,NaN,NaN,NaN,NaN
4,1,2022,False,5,Fertility,4.6,244.9,NaN,Not at all,Not at all,...,Woman,White,"Some university/ post-secondary, no degree",Yes,NaN,14,NaN,NaN,NaN,NaN

In [7]:
df_basic_hormones_glucose.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5659 entries, 0 to 5658
Data columns (total 48 columns):
 #   Column                                 Non-Null Count  Dtype
---  ------                                 --------------  -----
 0   id                                     5659 non-null   int64
 1   study_interval                         5659 non-null   int64
 2   is_weekend                             5659 non-null   bool
 3   day_in_study                           5659 non-null   int64
 4   phase                                  5658 non-null   object
 5   lh                                     5339 non-null   float64
 6   estrogen                               5338 non-null   float64
 7   pdg                                    1864 non-null   float64
 8   flow_volume                            3189 non-null   object
 9   flow_color                             3194 non-null   object
 10  appetite                               3330 non-null   object
 11  exerciselevel                          3330 non-null   object
 12  headaches                              3328 non-null   object
 13  cramps                                 3327 non-null   object
 14  sorebreasts                            3327 non-null   object
 15  fatigue                                3331 non-null   object
 16  sleepissue                             3329 non-null   object
 17  moodswing                              3320 non-null   object
 18  stress                                 3327 non-null   object
 19  foodcravings                           3327 non-null   object
 20  indigestion                            3325 non-null   object
 21  bloating                               3328 non-null   object
 22  glucose_12_2_am                        2939 non-null   float64
 23  glucose_2_4_am                         2920 non-null   float64
 24  glucose_4_6_am                         2922 non-null   float64
 25  glucose_6_8_am                         2934 non-null   float64
 26  glucose_8_10_am                        2949 non-null   float64
 27  glucose_10_12_am                       2949 non-null   float64
 28  glucose_12_2_pm                        2953 non-null   float64
 29  glucose_2_4_pm                         2969 non-null   float64
 30  glucose_4_6_pm                         2966 non-null   float64
 31  glucose_6_8_pm                         2966 non-null   float64
 32  glucose_8_10_pm                        2971 non-null   float64
 33  glucose_10_12_pm                       2956 non-null   float64
 34  glucose_min                            3108 non-null   float64
 35  glucose_max                            3108 non-null   float64
 36  glucose_avg                            3108 non-null   float64
 37  birth_year                             5659 non-null   int64
 38  gender                                 5659 non-null   object
 39  ethnicity                              5659 non-null   object
 40  education                              5659 non-null   object
 41  sexually_active                        5659 non-null   object
 42  self_report_menstrual_health_literacy  5569 non-null   object
 43  age_of_first_menarche                  5659 non-null   int64
 44  height2022                             2928 non-null   float64
 45  weight2022                             3302 non-null   float64
 46  height2024                             1538 non-null   float64
 47  weight2024                             2129 non-null   float64
dtypes: bool(1), float64(22), int64(5), object(20)
memory usage: 2.0+ MB

In [8]:
df_exercise = pd.read_csv('exercise_merged-2.csv')
df_exercise.head()

,id,study_interval,day_in_study,calories,steps,is_weekend,averageheartrate,calories_exercise,duration,steps_exercise,Cardio,Sports,Strength
0,1,2022,2,1591.0,838.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,2022,3,1755.0,2586.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1,2022,4,1552.0,1275.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1,2022,5,1456.0,436.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1,2022,6,1486.0,427.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

## merge all together

In [9]:
df_merge = (
    df_basic_hormones_glucose
    .merge(df_sleep, on=["id", "day_in_study"], how="left", suffixes=("", "_slp"))
    .merge(df_hr, on=["id", "day_in_study"], how="left", suffixes=("", "_hr"))
    .merge(df_exercise, on=["id", "day_in_study"], how="left", suffixes=("", "_exe")))

In [10]:
df_merge.head()

,id,study_interval,is_weekend,day_in_study,phase,lh,estrogen,pdg,flow_volume,flow_color,...,calories,steps,is_weekend_exe,averageheartrate,calories_exercise,duration,steps_exercise,Cardio,Sports,Strength
0,1,2022,True,1,Follicular,2.9,94.2,NaN,Not at all,Not at all,...,1542.0,992.0,True,104.0,61.0,1178000.0,651.0,0.0,1.0,0.0
1,1,2022,False,2,Follicular,1.2,226.3,NaN,Not at all,Not at all,...,1591.0,838.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1,2022,False,3,Follicular,3.5,276.8,NaN,Not at all,Not at all,...,1755.0,2586.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1,2022,False,4,Fertility,1.8,322.1,NaN,Not at all,Not at all,...,1552.0,1275.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1,2022,False,5,Fertility,4.6,244.9,NaN,Not at all,Not at all,...,1456.0,436.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [11]:
df_merge.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5659 entries, 0 to 5658
Columns: 149 entries, id to Strength
dtypes: bool(1), float64(113), int64(5), object(30)
memory usage: 6.4+ MB

In [12]:
pd.set_option('display.max_rows', None)
df_merge.isnull().sum()

id                                          0
study_interval                              0
is_weekend                                  0
day_in_study                                0
phase                                       1
lh                                        320
estrogen                                  321
pdg                                      3795
flow_volume                              2470
flow_color                               2465
appetite                                 2329
exerciselevel                            2329
headaches                                2331
cramps                                   2332
sorebreasts                              2332
fatigue                                  2328
sleepissue                               2330
moodswing                                2339
stress                                   2332
foodcravings                             2332
indigestion                              2334
bloating                                 2331
glucose_12_2_am                          2720
glucose_2_4_am                           2739
glucose_4_6_am                           2737
glucose_6_8_am                           2725
glucose_8_10_am                          2710
glucose_10_12_am                         2710
glucose_12_2_pm                          2706
glucose_2_4_pm                           2690
glucose_4_6_pm                           2693
glucose_6_8_pm                           2693
glucose_8_10_pm                          2688
glucose_10_12_pm                         2703
glucose_min                              2551
glucose_max                              2551
glucose_avg                              2551
birth_year                                  0
gender                                      0
ethnicity                                   0
education                                   0
sexually_active                             0
self_report_menstrual_health_literacy      90
age_of_first_menarche                       0
height2022                               2731
weight2022                               2357
height2024                               4121
weight2024                               3530
timestamp                                 581
composition_score                        2093
revitalization_score                      581
duration_score                           2093
deep_sleep_in_minutes                     582
resting_heart_rate                        581
restlessness                              581
study_interval_slp                        581
is_weekend_slp                            581
study_interval_resp                      3127
is_weekend_resp                          3127
full_sleep_breathing_rate_max            3127
full_sleep_breathing_rate_min            3127
full_sleep_breathing_rate_mean           3127
deep_sleep_breathing_rate_max            3127
deep_sleep_breathing_rate_min            3127
deep_sleep_breathing_rate_mean           3127
light_sleep_breathing_rate_max           3127
light_sleep_breathing_rate_min           3127
light_sleep_breathing_rate_mean          3127
rem_sleep_breathing_rate_max             3127
rem_sleep_breathing_rate_min             3127
rem_sleep_breathing_rate_mean            3127
sleep_start_timestamp                     581
sleep_end_timestamp                       581
minutesasleep                             581
minutesawake                              581
timeinbed                                 581
study_interval_sleep                      581
is_weekend_sleep                          581
study_interval_comp                       653
is_weekend_comp                           653
temperature_samples                       653
nightly_temperature                       653
study_interval_hr                         209
is_weekend_x                              209
in_default_zone_3                         209
in_default_zone_2                         209
in_default_zone_1                         209
below_default_zone_1                      209
is_weekend_y                              220
12am_bpm                                  544
2am_bpm                                   450
4am_bpm                                   405
6am_bpm                                   376
8am_bpm                                   402
10am_bpm                                  409
12pm_bpm                                  391
2pm_bpm                                   433
4pm_bpm                                   482
6pm_bpm                                   499
8pm_bpm                                   507
10pm_bpm                                  510
is_weekend_hr                             908
12am_rmssd                               2424
12am_lf                                  2424
12am_hf                                  2424
2am_rmssd                                1339
2am_lf                                   1339
2am_hf                                   1339
4am_rmssd                                1096
4am_lf                                   1096
4am_hf                                   1096
6am_rmssd                                1349
6am_lf                                   1349
6am_hf                                   1349
8am_rmssd                                2651
8am_lf                                   2651
8am_hf                                   2651
10am_rmssd                               4506
10am_lf                                  4506
10am_hf                                  4506
12pm_rmssd                               5319
12pm_lf                                  5319
12pm_hf                                  5319
2pm_rmssd                                5523
2pm_lf                                   5523
2pm_hf                                   5523
4pm_rmssd                                5584
4pm_lf                                   5584
4pm_hf                                   5584
6pm_rmssd                                5597
6pm_lf                                   5597
6pm_hf                                   5597
8pm_rmssd                                5521
8pm_lf                                   5521
8pm_hf                                   5521
10pm_rmssd                               4449
10pm_lf                                  4449
10pm_hf                                  4449
study_interval_exe                          4
calories                                    4
steps                                     126
is_weekend_exe                           3915
averageheartrate                         3921
calories_exercise                        3915
duration                                 3915
steps_exercise                           3915
Cardio                                   3915
Sports                                   3915
Strength                                 3915
dtype: int64

In [17]:
df_merge["age"] = 2022 - df_merge['birth_year']

In [21]:
df_2022 = df_merge[df_merge['study_interval'] == 2022]

In [22]:
df_2022['age'].mean()

20.83991346673878

In [24]:
df_2022['gender'].value_counts()

gender
Woman                3248
Non-binary            180
Gender Fluid           90
Other                  90
Prefer not to say      90
Name: count, dtype: int64

In [14]:
def check_unique(df, name):
    is_unique = not df.duplicated(["id", "day_in_study"]).any()
    dup_count = df.duplicated(["id", "day_in_study"], keep=False).sum()
    print(f"{name}: {'✅ Unique' if is_unique else '⚠️ Not Unique'}, it has {dup_count} duplicates")


check_unique(df_sleep, "df_sleep")

df_sleep: ✅ Unique, it has 0 duplicates

In [15]:
df_merge.to_csv('df_merge.csv')