# Sleep Table

In [93]:
import pandas as pd
import numpy as np

## Data Input

In [94]:
df_sleep = pd.read_csv('sleep.csv')
df_sleep.head()

,id,study_interval,is_weekend,sleep_start_day_in_study,sleep_start_timestamp,sleep_end_day_in_study,sleep_end_timestamp,duration,minutestofallasleep,minutesasleep,minutesawake,minutesafterwakeup,timeinbed,efficiency,type,infocode,levels,mainsleep
0,1,2022,False,4,00:12:30,4,07:42:00,26940000,0,384,65,4,449,93,stages,0,"{'summary': {'deep': {'count': 4, 'minutes': 9...",True
1,1,2022,False,10,00:28:30,10,10:49:30,37260000,0,602,19,0,621,97,classic,1,"{'summary': {'restless': {'count': 12, 'minute...",True
2,1,2022,False,11,01:19:30,11,08:03:00,24180000,0,370,33,2,403,97,stages,0,"{'summary': {'deep': {'count': 2, 'minutes': 5...",True
3,1,2022,False,12,00:46:00,12,08:06:00,26400000,0,398,42,0,440,96,stages,0,"{'summary': {'deep': {'count': 1, 'minutes': 5...",True
4,1,2022,False,32,23:51:00,33,06:48:00,25020000,0,392,25,0,417,99,stages,0,"{'summary': {'deep': {'count': 3, 'minutes': 8...",True

In [95]:
df_sleep_score = pd.read_csv('sleep_score.csv')
df_sleep_score.head()

,id,study_interval,is_weekend,day_in_study,timestamp,overall_score,composition_score,revitalization_score,duration_score,deep_sleep_in_minutes,resting_heart_rate,restlessness
0,1,2022,False,4,07:42:00,80,21.0,22,37.0,93.0,84,0.056404
1,1,2022,True,7,10:04:30,81,18.0,21,42.0,86.0,82,0.035122
2,1,2022,False,11,08:03:00,83,21.0,23,39.0,53.0,76,0.047014
3,1,2022,False,12,08:06:00,80,19.0,22,39.0,49.0,77,0.051282
4,1,2022,False,20,09:35:00,82,18.0,19,45.0,113.0,76,0.075188

In [96]:
df_computed_temp = pd.read_csv('computed_temperature.csv')
df_computed_temp.head()

,id,study_interval,is_weekend,sleep_start_day_in_study,sleep_start_timestamp,sleep_end_day_in_study,sleep_end_timestamp,type,temperature_samples,nightly_temperature,baseline_relative_sample_sum,baseline_relative_sample_sum_of_squares,baseline_relative_nightly_standard_deviation,baseline_relative_sample_standard_deviation
0,1,2022,True,1,00:08:00,1,10:25:30,SKIN,414,34.616087,NaN,NaN,NaN,NaN
1,1,2022,False,1,23:54:00,2,07:10:00,SKIN,258,33.780659,NaN,NaN,NaN,NaN
2,1,2022,False,3,00:14:00,3,09:04:00,SKIN,353,34.634929,6.651304,1554.843599,0.487865,2.101622
3,1,2022,False,4,00:12:30,4,07:42:00,SKIN,446,34.050056,-126.224891,1161.909368,0.424570,1.839029
4,1,2022,False,6,00:22:00,6,06:38:00,SKIN,269,34.223197,0.000000,766.896151,0.368295,1.803428

In [97]:
df_wrist_temp = pd.read_csv('wrist_temperature.csv')
df_wrist_temp.head()

,id,study_interval,is_weekend,day_in_study,timestamp,temperature_diff_from_baseline
0,1,2022,False,3,00:00:00,0.023913
1,1,2022,False,3,00:01:00,-0.021087
2,1,2022,False,3,00:02:00,-0.101087
3,1,2022,False,3,00:03:00,-0.196087
4,1,2022,False,3,00:04:00,-0.236087

In [98]:
df_oxygen = pd.read_csv('estimated_oxygen_variation.csv')
df_oxygen.head()

,id,study_interval,is_weekend,day_in_study,timestamp,infrared_to_red_signal_ratio
0,1,2022,True,1,00:16:29,16.0
1,1,2022,True,1,00:17:29,8.0
2,1,2022,True,1,00:18:29,-3.0
3,1,2022,True,1,00:19:29,-9.0
4,1,2022,True,1,00:20:29,15.0

In [99]:
df_respiratory = pd.read_csv('respiratory_rate_summary.csv')
df_respiratory.head()

,id,study_interval,is_weekend,day_in_study,timestamp,full_sleep_breathing_rate,full_sleep_standard_deviation,full_sleep_signal_to_noise,deep_sleep_breathing_rate,deep_sleep_standard_deviation,deep_sleep_signal_to_noise,light_sleep_breathing_rate,light_sleep_standard_deviation,light_sleep_signal_to_noise,rem_sleep_breathing_rate,rem_sleep_standard_deviation,rem_sleep_signal_to_noise
0,2,2022,True,8,08:20:30,15.6,1.3,17.943,15.6,1.3,17.943,15.0,1.6,14.618,15.6,1.4,5.826
1,2,2022,False,9,08:45:00,15.6,1.0,15.798,15.6,1.0,15.798,15.0,1.7,23.613,15.0,2.6,6.361
2,2,2022,False,10,08:34:00,16.0,1.3,10.539,16.0,1.3,10.539,15.2,1.5,19.845,14.4,2.2,8.378
3,2,2022,False,11,09:14:30,15.8,0.9,13.018,15.8,0.9,13.018,15.4,1.7,18.253,15.8,2.8,5.423
4,2,2022,False,11,08:55:00,15.8,0.9,13.018,15.8,0.9,13.018,15.4,1.7,16.092,15.8,2.8,5.573

## Drop Duplicated

In [100]:
df_computed_temp.drop_duplicates(inplace=True)
df_sleep.drop_duplicates(inplace = True)
df_sleep_score.drop_duplicates(inplace = True)                            
df_respiratory.drop_duplicates(inplace = True)
df_oxygen.drop_duplicates(inplace = True)
df_wrist_temp.drop_duplicates(inplace = True)

## Preprocessing According to Tables

In [101]:
def check_unique(df, name):
    is_unique = not df.duplicated(["id","study_interval", "day_in_study"]).any()
    dup_count = df.duplicated(["id","study_interval", "day_in_study"], keep=False).sum()
    print(f"{name}: {' Unique' if is_unique else ' Not Unique'}, it has {dup_count} duplicates")

### df_computed_temp

In [102]:
df_computed_temp.info()

<class 'pandas.core.frame.DataFrame'>
Index: 5179 entries, 0 to 5574
Data columns (total 14 columns):
 #   Column                                        Non-Null Count  Dtype
---  ------                                        --------------  -----
 0   id                                            5179 non-null   int64
 1   study_interval                                5179 non-null   int64
 2   is_weekend                                    5179 non-null   bool
 3   sleep_start_day_in_study                      5179 non-null   int64
 4   sleep_start_timestamp                         5179 non-null   object
 5   sleep_end_day_in_study                        5179 non-null   int64
 6   sleep_end_timestamp                           5179 non-null   object
 7   type                                          5179 non-null   object
 8   temperature_samples                           5179 non-null   int64
 9   nightly_temperature                           5179 non-null   float64
 10  baseline_relative_sample_sum                  5028 non-null   float64
 11  baseline_relative_sample_sum_of_squares       5028 non-null   float64
 12  baseline_relative_nightly_standard_deviation  5028 non-null   float64
 13  baseline_relative_sample_standard_deviation   5028 non-null   float64
dtypes: bool(1), float64(5), int64(5), object(3)
memory usage: 571.5+ KB

In [103]:
df_computed_temp.columns

Index(['id', 'study_interval', 'is_weekend', 'sleep_start_day_in_study',
       'sleep_start_timestamp', 'sleep_end_day_in_study',
       'sleep_end_timestamp', 'type', 'temperature_samples',
       'nightly_temperature', 'baseline_relative_sample_sum',
       'baseline_relative_sample_sum_of_squares',
       'baseline_relative_nightly_standard_deviation',
       'baseline_relative_sample_standard_deviation'],
      dtype='object')

In [104]:
df_computed_temp.drop(columns = ['sleep_start_day_in_study', 
                                 'type',
                                 'baseline_relative_sample_sum',
                                 'baseline_relative_sample_sum_of_squares',
                                 'baseline_relative_nightly_standard_deviation',
                                 'baseline_relative_sample_standard_deviation'], inplace = True)

In [105]:
df_computed_temp.rename(columns={'sleep_end_day_in_study': 'day_in_study'}, inplace=True)

In [106]:
df_computed_temp.info()

<class 'pandas.core.frame.DataFrame'>
Index: 5179 entries, 0 to 5574
Data columns (total 8 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   id                     5179 non-null   int64
 1   study_interval         5179 non-null   int64
 2   is_weekend             5179 non-null   bool
 3   sleep_start_timestamp  5179 non-null   object
 4   day_in_study           5179 non-null   int64
 5   sleep_end_timestamp    5179 non-null   object
 6   temperature_samples    5179 non-null   int64
 7   nightly_temperature    5179 non-null   float64
dtypes: bool(1), float64(1), int64(4), object(2)
memory usage: 328.7+ KB

In [107]:
df_computed_temp.isnull().sum()

id                       0
study_interval           0
is_weekend               0
sleep_start_timestamp    0
day_in_study             0
sleep_end_timestamp      0
temperature_samples      0
nightly_temperature      0
dtype: int64

In [108]:
check_unique(df_computed_temp, "df_computed_temp")

df_computed_temp:  Not Unique, it has 52 duplicates

In [109]:
df_computed_temp[df_computed_temp.duplicated(subset=['id', 'day_in_study'], keep=False)]

,id,study_interval,is_weekend,sleep_start_timestamp,day_in_study,sleep_end_timestamp,temperature_samples,nightly_temperature
579,9,2024,False,03:14:30,905,09:08:30,354,31.809703
580,9,2024,False,01:57:00,905,10:08:30,492,32.572043
581,9,2024,False,01:27:30,905,10:08:00,520,32.086000
582,9,2024,False,23:14:00,905,09:50:30,629,33.955620
2049,20,2024,False,03:14:30,891,09:08:30,354,31.809703
2050,20,2024,False,01:27:30,891,10:08:00,520,32.086000
2052,20,2024,False,01:18:30,891,06:56:30,331,34.012674
2053,20,2024,False,23:14:00,891,09:50:30,629,33.955620
2261,22,2024,False,03:14:30,852,09:08:30,354,31.809703
2263,22,2024,False,01:27:30,852,10:08:00,520,32.086000
2264,22,2024,False,01:18:30,852,06:56:30,331,34.012674
2265,22,2024,False,23:14:00,852,09:50:30,629,33.955620
2607,26,2024,False,03:14:30,856,09:08:30,354,31.809703
2608,26,2024,False,01:18:30,856,06:56:30,331,34.012674
2609,26,2024,False,00:44:00,856,08:26:30,462,33.690530
2610,26,2024,False,23:14:00,856,09:50:30,629,33.955620
3041,30,2024,False,03:14:30,856,09:08:30,354,31.809703
3042,30,2024,False,01:57:00,856,10:08:30,492,32.572043
3044,30,2024,False,01:27:30,856,10:08:00,520,32.086000
3045,30,2024,False,23:14:00,856,09:50:30,629,33.955620
3365,33,2024,False,03:14:30,856,09:08:30,354,31.809703
3366,33,2024,False,01:27:30,856,10:08:00,520,32.086000
3367,33,2024,False,01:18:30,856,06:56:30,331,34.012674
3369,33,2024,False,23:14:00,856,09:50:30,629,33.955620
3758,38,2024,False,03:14:30,853,09:08:30,354,31.809703
3759,38,2024,False,01:27:30,853,10:08:00,520,32.086000
3760,38,2024,False,01:18:30,853,06:56:30,331,34.012674
3761,38,2024,False,23:14:00,853,09:50:30,629,33.955620
4120,41,2024,False,03:14:30,842,09:08:30,354,31.809703
4121,41,2024,False,01:27:30,842,10:08:00,520,32.086000
4122,41,2024,False,01:18:30,842,06:56:30,331,34.012674
4123,41,2024,False,23:14:00,842,09:50:30,629,33.955620
4339,42,2024,False,03:14:30,849,09:08:30,354,31.809703
4340,42,2024,False,01:27:30,849,10:08:00,520,32.086000
4341,42,2024,False,01:18:30,849,06:56:30,331,34.012674
4342,42,2024,False,23:42:00,849,06:52:30,430,33.734849
4566,43,2024,False,03:14:30,849,09:08:30,354,31.809703
4567,43,2024,False,01:27:30,849,10:08:00,520,32.086000
4568,43,2024,False,01:18:30,849,06:56:30,331,34.012674
4569,43,2024,False,23:14:00,849,09:50:30,629,33.955620
5013,47,2024,False,04:50:00,838,10:53:30,352,33.081847
5015,47,2024,False,03:14:30,838,09:08:30,354,31.809703
5016,47,2024,False,01:27:30,838,10:08:00,520,32.086000
5017,47,2024,False,23:14:00,838,09:50:30,629,33.955620
5220,48,2024,False,03:14:30,849,09:08:30,354,31.809703
5221,48,2024,False,01:27:30,849,10:08:00,520,32.086000
5222,48,2024,False,01:18:30,849,06:56:30,331,34.012674
5223,48,2024,False,23:14:00,849,09:50:30,629,33.955620
5439,50,2024,False,03:14:30,849,09:08:30,354,31.809703
5440,50,2024,False,01:18:30,849,06:56:30,331,34.012674
5441,50,2024,False,00:44:00,849,08:26:30,462,33.690530
5443,50,2024,False,23:14:00,849,09:50:30,629,33.955620

In [110]:
df_computed_temp = (
    df_computed_temp
    .groupby(['id', 'day_in_study'], as_index=False)
    .mean(numeric_only=True)
)

In [111]:
check_unique(df_computed_temp, "df_computed_temp")

df_computed_temp:  Unique, it has 0 duplicates

### df_wrist_temp

In [112]:
# df_wrist_temp.info()

In [113]:
# df_wrist_temp_1 = df_wrist_temp.copy()

# df_wrist_temp_1['timestamp'] = pd.to_datetime(
#     df_wrist_temp_1['timestamp'], 
#     format='%H:%M:%S', 
#     errors='coerce'
# )
# df_wrist_temp_1['timestamp'] = df_wrist_temp_1['timestamp'].dt.strftime('%H:%M:%S')

In [114]:
# df_wrist_temp_1

In [115]:
# target_times = ["00:00:00","02:00:00", "04:00:00", "06:00:00", 
#                 "08:00:00","10:00:00","12:00:00","14:00:00",
#                 "16:00:00","18:00:00","20:00:00","22:00:00"]
# targets_td = pd.to_timedelta(target_times)

In [116]:
# df_aux = df_wrist_temp_1.assign(key=1)
# targets_df = pd.DataFrame({'target_time': targets_td}).assign(key=1)
# df_cross = df_aux.merge(targets_df, on='key', how='outer').drop(columns='key')

In [117]:
# df_cross = df_cross.dropna(subset=['timestamp', 'target_time'])
# df_cross['diff'] = (df_cross['timestamp'] - df_cross['target_time']).abs()

In [118]:
# group_cols = ['id', 'day_in_study','study_interval', 'target_time'] 
# idx = df_cross.groupby(group_cols)['diff'].idxmin()
# nearest_rows = df_cross.loc[idx].sort_values(['id', 'day_in_study', 'target_time'])

In [119]:
# from datetime import timedelta
# tolerance = timedelta(hours=2)
# df_cross = df_cross[df_cross['diff'] <= tolerance]

In [120]:
# keep_cols = [c for c in df_wrist_temp_1.columns] + ['target_time', 'diff']
# result = nearest_rows[keep_cols].reset_index(drop=True)

In [121]:
# result

In [122]:
# import pandas as pd

# df_wrist_temp_modified = df_wrist_temp_1.copy()

# df_wrist_temp_modified['timestamp'] = df_wrist_temp_modified['timestamp'].astype(str).str.strip()

# df_wrist_temp_modified = df_wrist_temp_modified[df_wrist_temp_modified['timestamp'].str.match(r'^\d{2}:\d{2}:\d{2}$', na=False)]

# df_wrist_temp_modified['timestamp'] = df_wrist_temp_modified['timestamp'].astype(str)

# df_wrist_temp_modified['hour'] = df_wrist_temp_modified['timestamp'].str.slice(0, 2).astype(int)

# target_hours = [2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22]
# df_wrist_temp_modified = df_wrist_temp_modified[df_wrist_temp_modified['hour'].isin(target_hours)]

# df_wrist_temp_modified['col_name'] = df_wrist_temp_modified['hour'].astype(str) + '_wrist_temp'

# df_wrist_temp_modified = df_wrist_temp_modified.pivot_table(
#     index=['id', 'study_interval', 'is_weekend', 'day_in_study'],
#     columns='col_name',
#     values='temperature_diff_from_baseline',
#     aggfunc='first'
# ).reset_index()

# df_wrist_temp_modified.columns.name = None

# cols = ['id', 'study_interval', 'is_weekend', 'day_in_study'] + [f"{h}_wrist_temp" for h in target_hours]

# df_wrist_temp_modified = df_wrist_temp_modified.reindex(columns=cols, fill_value=pd.NA)

# df_wrist_temp_modified.head()

In [123]:
# df_wrist_temp_modified.info()

In [124]:
# daily_stats = (
#     df_wrist_temp_1
#     .groupby("day_in_study", as_index=False)["temperature_diff_from_baseline"]
#     .agg([
#         ("temp_max", "max"),
#         ("temp_min", "min"),
#         ("temp_avg", "mean")
#     ])
# )

In [125]:
# df_wrist_temp_modified = df_wrist_temp_modified.merge(
#     daily_stats,
#     on="day_in_study",
#     how="left"
# )

In [126]:
# df_wrist_temp_modified.info()

### df_oxygen

In [127]:
#  df_oxygen.info()

In [128]:
# df_oxygen_1 = df_oxygen.copy()

# df_oxygen_1['timestamp'] = pd.to_datetime(
#     df_oxygen_1['timestamp'], 
#     format='%H:%M:%S', 
#     errors='coerce'
# )
# df_oxygen_1['timestamp'] = df_oxygen_1['timestamp'].dt.strftime('%H:%M:%S')

In [129]:
# target_times = ["00:00:00","02:00:00", "04:00:00", "06:00:00", 
#                 "08:00:00","10:00:00","12:00:00","14:00:00",
#                 "16:00:00","18:00:00","20:00:00","22:00:00"]
# targets_td = pd.to_timedelta(target_times)

In [130]:
# df_aux = df_oxygen_1.assign(key=1)
# targets_df = pd.DataFrame({'target_time': targets_td}).assign(key=1)
# df_cross = df_aux.merge(targets_df, on='key', how='outer').drop(columns='key')

In [131]:
# df_cross = df_cross.dropna(subset=['timestamp', 'target_time'])
# df_cross['diff'] = (df_cross['timestamp'] - df_cross['target_time']).abs()

In [132]:
# group_cols = ['id', 'day_in_study','study_interval', 'target_time']  # 也可以加 'study_interval' 等
# idx = df_cross.groupby(group_cols)['diff'].idxmin()
# nearest_rows = df_cross.loc[idx].sort_values(['id', 'day_in_study', 'target_time'])

In [133]:
# from datetime import timedelta
# tolerance = timedelta(hours=2)
# df_cross = df_cross[df_cross['diff'] <= tolerance]

In [134]:
# keep_cols = [c for c in df_oxygen_1.columns] + ['target_time', 'diff']
# result = nearest_rows[keep_cols].reset_index(drop=True)

In [135]:
# import pandas as pd

# df_oxygen_modified = df_oxygen_1.copy()

# df_oxygen_modified['timestamp'] = df_oxygen_modified['timestamp'].astype(str).str.strip()

# df_oxygen_modified = df_oxygen_modified[df_oxygen_modified['timestamp'].str.match(r'^\d{2}:\d{2}:\d{2}$', na=False)]

# df_oxygen_modified['timestamp'] = df_oxygen_modified['timestamp'].astype(str)

# df_oxygen_modified['hour'] = df_oxygen_modified['timestamp'].str.slice(0, 2).astype(int)

# target_hours = [2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22]
# df_oxygen_modified = df_oxygen_modified[df_oxygen_modified['hour'].isin(target_hours)]

# df_oxygen_modified['col_name'] = df_oxygen_modified['hour'].astype(str) + '_wrist_temp'

# df_oxygen_modified = df_oxygen_modified.pivot_table(
#     index=['id', 'study_interval', 'is_weekend', 'day_in_study'],
#     columns='col_name',
#     values='infrared_to_red_signal_ratio',
#     aggfunc='first'
# ).reset_index()

# df_oxygen_modified.columns.name = None

# cols = ['id', 'study_interval', 'is_weekend', 'day_in_study'] + [f"{h}_oxy" for h in target_hours]

# df_oxygen_modified = df_oxygen_modified.reindex(columns=cols, fill_value=pd.NA)

# df_oxygen_modified.head()

In [136]:
# df_oxygen_modified.info()

In [137]:
# daily_stats_o = (
#     df_oxygen_1
#     .groupby("day_in_study", as_index=False)["infrared_to_red_signal_ratio"]
#     .agg([
#         ("oxy_max", "max"),
#         ("oxy_min", "min"),
#         ("oxy_avg", "mean")
#     ])
# )

In [138]:
# df_oxygen_modified = df_oxygen_modified.merge(
#     daily_stats_o,
#     on="day_in_study",
#     how="left"
# )

In [139]:
# df_oxygen_modified.info()

In [140]:
# df_oxygen_modified.columns

In [141]:
# df_oxygen_modified.drop(columns = ['10_oxy',
#        '12_oxy', '14_oxy', '16_oxy', '18_oxy',
#        '20_oxy', '22_oxy'], inplace = True)

### df_respiratory

In [142]:
df_respiratory.info()

<class 'pandas.core.frame.DataFrame'>
Index: 5861 entries, 0 to 6300
Data columns (total 17 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   id                              5861 non-null   int64
 1   study_interval                  5861 non-null   int64
 2   is_weekend                      5861 non-null   bool
 3   day_in_study                    5861 non-null   int64
 4   timestamp                       5861 non-null   object
 5   full_sleep_breathing_rate       5861 non-null   float64
 6   full_sleep_standard_deviation   5861 non-null   float64
 7   full_sleep_signal_to_noise      5861 non-null   float64
 8   deep_sleep_breathing_rate       5861 non-null   float64
 9   deep_sleep_standard_deviation   5861 non-null   float64
 10  deep_sleep_signal_to_noise      5861 non-null   float64
 11  light_sleep_breathing_rate      5861 non-null   float64
 12  light_sleep_standard_deviation  5861 non-null   float64
 13  light_sleep_signal_to_noise     5861 non-null   float64
 14  rem_sleep_breathing_rate        5861 non-null   float64
 15  rem_sleep_standard_deviation    5861 non-null   float64
 16  rem_sleep_signal_to_noise       5861 non-null   float64
dtypes: bool(1), float64(12), int64(3), object(1)
memory usage: 784.1+ KB

In [143]:
df_respiratory.columns

Index(['id', 'study_interval', 'is_weekend', 'day_in_study', 'timestamp',
       'full_sleep_breathing_rate', 'full_sleep_standard_deviation',
       'full_sleep_signal_to_noise', 'deep_sleep_breathing_rate',
       'deep_sleep_standard_deviation', 'deep_sleep_signal_to_noise',
       'light_sleep_breathing_rate', 'light_sleep_standard_deviation',
       'light_sleep_signal_to_noise', 'rem_sleep_breathing_rate',
       'rem_sleep_standard_deviation', 'rem_sleep_signal_to_noise'],
      dtype='object')

In [144]:
df_respiratory.drop(columns = ['full_sleep_standard_deviation','full_sleep_signal_to_noise',
                               'deep_sleep_standard_deviation', 'deep_sleep_signal_to_noise',
                               'light_sleep_standard_deviation','light_sleep_signal_to_noise',
                               'rem_sleep_standard_deviation', 'rem_sleep_signal_to_noise'], inplace = True)

In [145]:
df_respiratory_1 = df_respiratory.copy()

df_respiratory_1['timestamp'] = pd.to_datetime(
    df_respiratory_1['timestamp'], 
    format='%H:%M:%S', 
    errors='coerce'
)
df_respiratory_1['timestamp'] = df_respiratory_1['timestamp'].dt.strftime('%H:%M:%S')

In [146]:
target_times = ["00:00:00","02:00:00", "04:00:00", "06:00:00", 
                "08:00:00","10:00:00","12:00:00","14:00:00",
                "16:00:00","18:00:00","20:00:00","22:00:00"]
targets_td = pd.to_timedelta(target_times)

In [147]:
df_aux = df_respiratory_1.assign(key=1)
targets_df = pd.DataFrame({'target_time': targets_td}).assign(key=1)
df_cross = df_aux.merge(targets_df, on='key', how='outer').drop(columns='key')

In [148]:
df_cross = df_cross.dropna(subset=['timestamp', 'target_time'])
df_cross['diff'] = (df_cross['timestamp'] - df_cross['target_time']).abs()

/var/tmp/ipykernel_5837/3714050880.py:2: PerformanceWarning: Adding/subtracting object-dtype array to TimedeltaArray not vectorized.
  df_cross['diff'] = (df_cross['timestamp'] - df_cross['target_time']).abs()

In [149]:
group_cols = ['id', 'day_in_study','study_interval', 'target_time']  # 也可以加 'study_interval' 等
idx = df_cross.groupby(group_cols)['diff'].idxmin()
nearest_rows = df_cross.loc[idx].sort_values(['id', 'day_in_study', 'target_time'])

In [150]:
tolerance = pd.Timedelta(hours=2)
nearest_rows = nearest_rows[nearest_rows['diff'] <= tolerance]

In [151]:
keep_cols = [c for c in df_respiratory_1.columns] + ['target_time', 'diff']
result = nearest_rows[keep_cols].reset_index(drop=True)

In [152]:
result

,id,study_interval,is_weekend,day_in_study,timestamp,full_sleep_breathing_rate,deep_sleep_breathing_rate,light_sleep_breathing_rate,rem_sleep_breathing_rate,target_time,diff
0,2,2022,True,8,08:20:30,15.6,15.6,15.0,15.6,0 days 08:00:00,0 days 00:20:30
1,2,2022,True,8,08:20:30,15.6,15.6,15.0,15.6,0 days 10:00:00,0 days 01:39:30
2,2,2022,False,9,08:45:00,15.6,15.6,15.0,15.0,0 days 08:00:00,0 days 00:45:00
3,2,2022,False,9,08:45:00,15.6,15.6,15.0,15.0,0 days 10:00:00,0 days 01:15:00
4,2,2022,False,10,08:34:00,16.0,16.0,15.2,14.4,0 days 08:00:00,0 days 00:34:00
...,...,...,...,...,...,...,...,...,...,...,...
10809,50,2024,False,949,08:36:00,17.8,17.8,17.2,-1.0,0 days 10:00:00,0 days 01:24:00
10810,50,2024,False,950,08:11:00,17.8,17.8,17.4,16.4,0 days 08:00:00,0 days 00:11:00
10811,50,2024,False,950,08:11:00,17.8,17.8,17.4,16.4,0 days 10:00:00,0 days 01:49:00
10812,50,2024,False,951,08:06:00,18.0,18.0,17.0,16.0,0 days 08:00:00,0 days 00:06:00
10813,50,2024,False,951,08:06:00,18.0,18.0,17.0,16.0,0 days 10:00:00,0 days 01:54:00

In [153]:
df_respiratory_modified = df_respiratory_1.copy()
df_respiratory_modified['timestamp'] = df_respiratory_modified['timestamp'].astype(str).str.strip()
df_respiratory_modified = df_respiratory_modified[df_respiratory_modified['timestamp'].str.match(r'^\d{2}:\d{2}:\d{2}$', na=False)]
df_respiratory_modified['hour'] = df_respiratory_modified['timestamp'].str.slice(0, 2).astype(int)

target_hours = [2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22]
df_respiratory_modified = df_respiratory_modified[df_respiratory_modified['hour'].isin(target_hours)]

df_respiratory_modified['col_name'] = df_respiratory_modified['hour'].astype(str) + '_respiratory'

df_respiratory_modified = df_respiratory_modified.pivot_table(
    index=['id', 'study_interval', 'is_weekend', 'day_in_study'],
    columns='col_name',
    values=['full_sleep_breathing_rate','deep_sleep_breathing_rate','light_sleep_breathing_rate','rem_sleep_breathing_rate'],
    aggfunc='first'
).reset_index()

df_respiratory_modified.columns = [
    f"{a}__{b}" if b else a
    for a, b in df_respiratory_modified.columns.to_flat_index()
]


metrics = ['full_sleep_breathing_rate','deep_sleep_breathing_rate','light_sleep_breathing_rate','rem_sleep_breathing_rate']
hour_cols = [f"{m}__{h}_respiratory" for m in metrics for h in target_hours]
wanted_cols = ['id','study_interval','is_weekend','day_in_study'] + hour_cols
df_respiratory_modified = df_respiratory_modified.reindex(columns=wanted_cols)

df_respiratory_modified.head(20)

,id,study_interval,is_weekend,day_in_study,full_sleep_breathing_rate__2_respiratory,full_sleep_breathing_rate__4_respiratory,full_sleep_breathing_rate__6_respiratory,full_sleep_breathing_rate__8_respiratory,full_sleep_breathing_rate__10_respiratory,full_sleep_breathing_rate__12_respiratory,...,rem_sleep_breathing_rate__4_respiratory,rem_sleep_breathing_rate__6_respiratory,rem_sleep_breathing_rate__8_respiratory,rem_sleep_breathing_rate__10_respiratory,rem_sleep_breathing_rate__12_respiratory,rem_sleep_breathing_rate__14_respiratory,rem_sleep_breathing_rate__16_respiratory,rem_sleep_breathing_rate__18_respiratory,rem_sleep_breathing_rate__20_respiratory,rem_sleep_breathing_rate__22_respiratory
0,2,2022,False,9,NaN,NaN,NaN,15.6,NaN,NaN,...,NaN,NaN,15.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2,2022,False,10,NaN,NaN,NaN,16.0,NaN,NaN,...,NaN,NaN,14.4,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2,2022,False,11,NaN,NaN,NaN,15.8,NaN,NaN,...,NaN,NaN,15.8,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2,2022,False,12,NaN,NaN,NaN,16.2,NaN,NaN,...,NaN,NaN,16.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2,2022,False,13,NaN,NaN,NaN,16.2,NaN,NaN,...,NaN,NaN,16.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,2,2022,False,16,NaN,NaN,NaN,16.6,NaN,NaN,...,NaN,NaN,16.8,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,2,2022,False,17,NaN,NaN,NaN,16.8,NaN,NaN,...,NaN,NaN,16.8,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,2,2022,False,18,NaN,NaN,NaN,16.2,NaN,NaN,...,NaN,NaN,14.4,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,2,2022,False,19,NaN,NaN,NaN,16.4,NaN,NaN,...,NaN,NaN,17.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,2,2022,False,20,NaN,NaN,NaN,15.2,NaN,NaN,...,NaN,NaN,16.2,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,2,2022,False,23,NaN,NaN,NaN,15.2,NaN,NaN,...,NaN,NaN,15.6,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,2,2022,False,33,NaN,NaN,16.0,NaN,NaN,NaN,...,NaN,15.6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,2,2022,False,37,NaN,NaN,NaN,16.0,NaN,NaN,...,NaN,NaN,15.6,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,2,2022,False,38,NaN,NaN,NaN,16.4,NaN,NaN,...,NaN,NaN,14.4,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,2,2022,False,40,NaN,NaN,NaN,16.8,NaN,NaN,...,NaN,NaN,15.8,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,2,2022,False,41,NaN,NaN,NaN,17.0,NaN,NaN,...,NaN,NaN,9.8,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,2,2022,False,44,NaN,NaN,NaN,16.8,NaN,NaN,...,NaN,NaN,13.4,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,2,2022,False,45,NaN,NaN,NaN,17.4,NaN,NaN,...,NaN,NaN,15.4,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,2,2022,False,46,NaN,NaN,NaN,17.2,NaN,NaN,...,NaN,NaN,19.4,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,2,2022,False,48,NaN,NaN,NaN,17.0,NaN,NaN,...,NaN,NaN,16.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [154]:
cols = [
    "full_sleep_breathing_rate",
    "deep_sleep_breathing_rate",
    "light_sleep_breathing_rate",
    "rem_sleep_breathing_rate"
]
resp_stats = (
    df_respiratory_1
    .groupby("day_in_study")[cols]
    .agg(["max", "min", "mean"])
    .reset_index()
)
resp_stats.columns = [
    f"{col}_{stat}" if stat != "" else col
    for col, stat in resp_stats.columns.to_flat_index()
]

In [155]:
df_respiratory_modified = df_respiratory_modified.merge(
    resp_stats,
    on="day_in_study",
    how="left"
)

In [156]:
df_respiratory_modified

,id,study_interval,is_weekend,day_in_study,full_sleep_breathing_rate__2_respiratory,full_sleep_breathing_rate__4_respiratory,full_sleep_breathing_rate__6_respiratory,full_sleep_breathing_rate__8_respiratory,full_sleep_breathing_rate__10_respiratory,full_sleep_breathing_rate__12_respiratory,...,full_sleep_breathing_rate_mean,deep_sleep_breathing_rate_max,deep_sleep_breathing_rate_min,deep_sleep_breathing_rate_mean,light_sleep_breathing_rate_max,light_sleep_breathing_rate_min,light_sleep_breathing_rate_mean,rem_sleep_breathing_rate_max,rem_sleep_breathing_rate_min,rem_sleep_breathing_rate_mean
0,2,2022,False,9,NaN,NaN,NaN,15.6,NaN,NaN,...,15.442857,19.4,12.2,15.442857,20.6,11.8,14.878571,18.2,-1.0,11.357143
1,2,2022,False,10,NaN,NaN,NaN,16.0,NaN,NaN,...,15.580645,18.8,12.2,15.612903,17.4,-1.0,14.277419,19.0,-1.0,12.580645
2,2,2022,False,11,NaN,NaN,NaN,15.8,NaN,NaN,...,15.544444,18.8,-1.0,14.622222,17.8,-1.0,14.494444,17.4,-1.0,12.011111
3,2,2022,False,12,NaN,NaN,NaN,16.2,NaN,NaN,...,14.606667,19.0,-1.0,14.653333,17.8,-1.0,13.900000,17.4,-1.0,11.240000
4,2,2022,False,13,NaN,NaN,NaN,16.2,NaN,NaN,...,15.696774,18.0,11.6,15.696774,17.4,11.6,14.883871,17.2,-1.0,12.703226
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2598,50,2024,True,910,NaN,NaN,NaN,18.4,NaN,NaN,...,15.420690,21.4,-1.0,15.503448,24.0,-1.0,14.324138,19.6,-1.0,12.689655
2599,50,2024,True,911,NaN,NaN,NaN,NaN,18.8,NaN,...,14.718750,24.2,-1.0,14.825000,19.8,-1.0,14.262500,29.8,-1.0,10.268750
2600,50,2024,True,932,NaN,NaN,NaN,NaN,17.2,NaN,...,15.726316,21.8,12.6,15.778947,18.6,12.4,15.063158,19.2,-1.0,12.557895
2601,50,2024,True,939,NaN,NaN,NaN,17.2,NaN,NaN,...,15.789474,19.6,12.8,15.936842,19.0,12.4,15.115789,17.8,-1.0,12.094737
2602,50,2024,True,945,NaN,NaN,NaN,18.6,NaN,NaN,...,13.162500,18.6,-1.0,13.037500,17.6,-1.0,12.475000,17.6,-1.0,10.562500

In [157]:
df_respiratory_modified.columns

Index(['id', 'study_interval', 'is_weekend', 'day_in_study',
       'full_sleep_breathing_rate__2_respiratory',
       'full_sleep_breathing_rate__4_respiratory',
       'full_sleep_breathing_rate__6_respiratory',
       'full_sleep_breathing_rate__8_respiratory',
       'full_sleep_breathing_rate__10_respiratory',
       'full_sleep_breathing_rate__12_respiratory',
       'full_sleep_breathing_rate__14_respiratory',
       'full_sleep_breathing_rate__16_respiratory',
       'full_sleep_breathing_rate__18_respiratory',
       'full_sleep_breathing_rate__20_respiratory',
       'full_sleep_breathing_rate__22_respiratory',
       'deep_sleep_breathing_rate__2_respiratory',
       'deep_sleep_breathing_rate__4_respiratory',
       'deep_sleep_breathing_rate__6_respiratory',
       'deep_sleep_breathing_rate__8_respiratory',
       'deep_sleep_breathing_rate__10_respiratory',
       'deep_sleep_breathing_rate__12_respiratory',
       'deep_sleep_breathing_rate__14_respiratory',
       'deep_sleep_breathing_rate__16_respiratory',
       'deep_sleep_breathing_rate__18_respiratory',
       'deep_sleep_breathing_rate__20_respiratory',
       'deep_sleep_breathing_rate__22_respiratory',
       'light_sleep_breathing_rate__2_respiratory',
       'light_sleep_breathing_rate__4_respiratory',
       'light_sleep_breathing_rate__6_respiratory',
       'light_sleep_breathing_rate__8_respiratory',
       'light_sleep_breathing_rate__10_respiratory',
       'light_sleep_breathing_rate__12_respiratory',
       'light_sleep_breathing_rate__14_respiratory',
       'light_sleep_breathing_rate__16_respiratory',
       'light_sleep_breathing_rate__18_respiratory',
       'light_sleep_breathing_rate__20_respiratory',
       'light_sleep_breathing_rate__22_respiratory',
       'rem_sleep_breathing_rate__2_respiratory',
       'rem_sleep_breathing_rate__4_respiratory',
       'rem_sleep_breathing_rate__6_respiratory',
       'rem_sleep_breathing_rate__8_respiratory',
       'rem_sleep_breathing_rate__10_respiratory',
       'rem_sleep_breathing_rate__12_respiratory',
       'rem_sleep_breathing_rate__14_respiratory',
       'rem_sleep_breathing_rate__16_respiratory',
       'rem_sleep_breathing_rate__18_respiratory',
       'rem_sleep_breathing_rate__20_respiratory',
       'rem_sleep_breathing_rate__22_respiratory',
       'full_sleep_breathing_rate_max', 'full_sleep_breathing_rate_min',
       'full_sleep_breathing_rate_mean', 'deep_sleep_breathing_rate_max',
       'deep_sleep_breathing_rate_min', 'deep_sleep_breathing_rate_mean',
       'light_sleep_breathing_rate_max', 'light_sleep_breathing_rate_min',
       'light_sleep_breathing_rate_mean', 'rem_sleep_breathing_rate_max',
       'rem_sleep_breathing_rate_min', 'rem_sleep_breathing_rate_mean'],
      dtype='object')

In [158]:
df_respiratory_modified.drop(columns = ['full_sleep_breathing_rate__2_respiratory',
       'full_sleep_breathing_rate__4_respiratory',
       'full_sleep_breathing_rate__6_respiratory',
       'full_sleep_breathing_rate__8_respiratory',
       'full_sleep_breathing_rate__10_respiratory',
       'full_sleep_breathing_rate__12_respiratory',
       'full_sleep_breathing_rate__14_respiratory',
       'full_sleep_breathing_rate__16_respiratory',
       'full_sleep_breathing_rate__18_respiratory',
       'full_sleep_breathing_rate__20_respiratory',
       'full_sleep_breathing_rate__22_respiratory',
       'deep_sleep_breathing_rate__2_respiratory',
       'deep_sleep_breathing_rate__4_respiratory',
       'deep_sleep_breathing_rate__6_respiratory',
       'deep_sleep_breathing_rate__8_respiratory',
       'deep_sleep_breathing_rate__10_respiratory',
       'deep_sleep_breathing_rate__12_respiratory',
       'deep_sleep_breathing_rate__14_respiratory',
       'deep_sleep_breathing_rate__16_respiratory',
       'deep_sleep_breathing_rate__18_respiratory',
       'deep_sleep_breathing_rate__20_respiratory',
       'deep_sleep_breathing_rate__22_respiratory',
       'light_sleep_breathing_rate__2_respiratory',
       'light_sleep_breathing_rate__4_respiratory',
       'light_sleep_breathing_rate__6_respiratory',
       'light_sleep_breathing_rate__8_respiratory',
       'light_sleep_breathing_rate__10_respiratory',
       'light_sleep_breathing_rate__12_respiratory',
       'light_sleep_breathing_rate__14_respiratory',
       'light_sleep_breathing_rate__16_respiratory',
       'light_sleep_breathing_rate__18_respiratory',
       'light_sleep_breathing_rate__20_respiratory',
       'light_sleep_breathing_rate__22_respiratory',
       'rem_sleep_breathing_rate__2_respiratory',
       'rem_sleep_breathing_rate__4_respiratory',
       'rem_sleep_breathing_rate__6_respiratory',
       'rem_sleep_breathing_rate__8_respiratory',
       'rem_sleep_breathing_rate__10_respiratory',
       'rem_sleep_breathing_rate__12_respiratory',
       'rem_sleep_breathing_rate__14_respiratory',
       'rem_sleep_breathing_rate__16_respiratory',
       'rem_sleep_breathing_rate__18_respiratory',
       'rem_sleep_breathing_rate__20_respiratory',
       'rem_sleep_breathing_rate__22_respiratory'], inplace = True)

In [159]:
df_respiratory_modified.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2603 entries, 0 to 2602
Data columns (total 16 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   id                               2603 non-null   int64
 1   study_interval                   2603 non-null   int64
 2   is_weekend                       2603 non-null   bool
 3   day_in_study                     2603 non-null   int64
 4   full_sleep_breathing_rate_max    2603 non-null   float64
 5   full_sleep_breathing_rate_min    2603 non-null   float64
 6   full_sleep_breathing_rate_mean   2603 non-null   float64
 7   deep_sleep_breathing_rate_max    2603 non-null   float64
 8   deep_sleep_breathing_rate_min    2603 non-null   float64
 9   deep_sleep_breathing_rate_mean   2603 non-null   float64
 10  light_sleep_breathing_rate_max   2603 non-null   float64
 11  light_sleep_breathing_rate_min   2603 non-null   float64
 12  light_sleep_breathing_rate_mean  2603 non-null   float64
 13  rem_sleep_breathing_rate_max     2603 non-null   float64
 14  rem_sleep_breathing_rate_min     2603 non-null   float64
 15  rem_sleep_breathing_rate_mean    2603 non-null   float64
dtypes: bool(1), float64(12), int64(3)
memory usage: 307.7 KB

In [160]:
check_unique(df_respiratory_modified, "df_respiratory_modified")

df_respiratory_modified:  Unique, it has 0 duplicates

### df_sleep

In [161]:
df_sleep.info()

<class 'pandas.core.frame.DataFrame'>
Index: 14312 entries, 0 to 14764
Data columns (total 18 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   id                        14312 non-null  int64
 1   study_interval            14312 non-null  int64
 2   is_weekend                14312 non-null  bool
 3   sleep_start_day_in_study  14312 non-null  int64
 4   sleep_start_timestamp     14312 non-null  object
 5   sleep_end_day_in_study    14312 non-null  int64
 6   sleep_end_timestamp       14312 non-null  object
 7   duration                  14312 non-null  int64
 8   minutestofallasleep       14312 non-null  int64
 9   minutesasleep             14312 non-null  int64
 10  minutesawake              14312 non-null  int64
 11  minutesafterwakeup        14312 non-null  int64
 12  timeinbed                 14312 non-null  int64
 13  efficiency                14312 non-null  int64
 14  type                      14312 non-null  object
 15  infocode                  14312 non-null  int64
 16  levels                    14312 non-null  object
 17  mainsleep                 14312 non-null  bool
dtypes: bool(2), int64(12), object(4)
memory usage: 1.9+ MB

In [162]:
df_sleep.columns

Index(['id', 'study_interval', 'is_weekend', 'sleep_start_day_in_study',
       'sleep_start_timestamp', 'sleep_end_day_in_study',
       'sleep_end_timestamp', 'duration', 'minutestofallasleep',
       'minutesasleep', 'minutesawake', 'minutesafterwakeup', 'timeinbed',
       'efficiency', 'type', 'infocode', 'levels', 'mainsleep'],
      dtype='object')

In [163]:
df_sleep.drop(columns = ['sleep_start_day_in_study','duration', 'minutestofallasleep',
                         'minutesafterwakeup','efficiency', 'type', 'infocode', 'levels'], inplace = True)

In [164]:
df_sleep.rename(columns={'sleep_end_day_in_study': 'day_in_study'}, inplace=True)

In [165]:
df_sleep.info()

<class 'pandas.core.frame.DataFrame'>
Index: 14312 entries, 0 to 14764
Data columns (total 10 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   id                     14312 non-null  int64
 1   study_interval         14312 non-null  int64
 2   is_weekend             14312 non-null  bool
 3   sleep_start_timestamp  14312 non-null  object
 4   day_in_study           14312 non-null  int64
 5   sleep_end_timestamp    14312 non-null  object
 6   minutesasleep          14312 non-null  int64
 7   minutesawake           14312 non-null  int64
 8   timeinbed              14312 non-null  int64
 9   mainsleep              14312 non-null  bool
dtypes: bool(2), int64(6), object(2)
memory usage: 1.0+ MB

In [166]:
check_unique(df_sleep, "df_sleep")

df_sleep:  Not Unique, it has 11481 duplicates

In [167]:
df_sleep[df_sleep.duplicated(subset=['id', 'day_in_study'], keep=False)]

,id,study_interval,is_weekend,sleep_start_timestamp,day_in_study,sleep_end_timestamp,minutesasleep,minutesawake,timeinbed,mainsleep
7,1,2022,False,14:13:00,38,15:44:30,88,3,91,False
8,1,2022,False,00:53:00,38,08:30:00,405,52,457,True
10,1,2022,False,23:33:30,53,04:18:00,256,28,284,True
13,1,2022,False,22:58:30,69,07:32:00,461,52,513,True
16,2,2022,False,15:42:00,4,16:52:30,70,0,70,False
...,...,...,...,...,...,...,...,...,...,...
14760,50,2024,False,04:47:00,948,09:29:00,259,23,282,True
14761,50,2024,False,04:09:30,948,11:44:00,389,65,454,True
14762,50,2024,False,01:18:30,948,02:47:00,79,9,88,False
14763,50,2024,False,00:52:00,948,06:40:30,300,48,348,True
14764,50,2024,False,00:28:30,948,07:33:30,341,84,425,True

In [168]:
import pandas as pd

SUM_COLS = ['minutesasleep', 'minutesawake', 'timeinbed']

def combine_sleep(group: pd.DataFrame) -> pd.Series:
    sums = group[SUM_COLS].sum(numeric_only=True)

    main = group[group['mainsleep'] == True]
    if main.empty:
        main = group.loc[[group['minutesasleep'].idxmax()]]

    main = main.iloc[0]

    out = {
        'sleep_start_timestamp': main['sleep_start_timestamp'],
        'sleep_end_timestamp'  : main['sleep_end_timestamp'],
        'minutesasleep'        : sums['minutesasleep'],
        'minutesawake'         : sums['minutesawake'],
        'timeinbed'            : sums['timeinbed'],
        'study_interval'       : group['study_interval'].iloc[0],
        'is_weekend'           : group['is_weekend'].any(),
    }
    return pd.Series(out)

df_sleep_agg = (
    df_sleep
    .groupby(['id', 'day_in_study'], as_index=True)
    .apply(combine_sleep)
    .reset_index()
)

print(df_sleep_agg.head())

   id  day_in_study sleep_start_timestamp sleep_end_timestamp  minutesasleep  \
0   1             1              00:08:00            10:25:30            596
1   1             2              23:54:00            07:10:00            508
2   1             3              00:14:00            09:04:00            502
3   1             4              00:12:30            07:42:00            384
4   1             6              00:22:00            06:38:00            365

   minutesawake  timeinbed  study_interval  is_weekend
0            21        617            2022        True
1             9        517            2022        True
2            28        530            2022       False
3            65        449            2022       False
4            11        376            2022       False

/var/tmp/ipykernel_5837/297235244.py:29: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  .apply(combine_sleep)

In [169]:
check_unique(df_sleep_agg, "df_sleep_agg")

df_sleep_agg:  Unique, it has 0 duplicates

### df_sleep_score

In [170]:
df_sleep_score.info()

<class 'pandas.core.frame.DataFrame'>
Index: 5247 entries, 0 to 5307
Data columns (total 12 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   id                     5247 non-null   int64
 1   study_interval         5247 non-null   int64
 2   is_weekend             5247 non-null   bool
 3   day_in_study           5247 non-null   int64
 4   timestamp              5247 non-null   object
 5   overall_score          5247 non-null   int64
 6   composition_score      3705 non-null   float64
 7   revitalization_score   5247 non-null   int64
 8   duration_score         3705 non-null   float64
 9   deep_sleep_in_minutes  5243 non-null   float64
 10  resting_heart_rate     5247 non-null   int64
 11  restlessness           5247 non-null   float64
dtypes: bool(1), float64(4), int64(6), object(1)
memory usage: 497.0+ KB

In [171]:
df_sleep_score.drop(columns = 'overall_score', inplace = True)

In [172]:
check_unique(df_sleep_score, "df_sleep_score")

df_sleep_score:  Not Unique, it has 337 duplicates

In [173]:
df_sleep_score[df_sleep_score.duplicated(subset=['id', 'day_in_study'], keep=False)]

,id,study_interval,is_weekend,day_in_study,timestamp,composition_score,revitalization_score,duration_score,deep_sleep_in_minutes,resting_heart_rate,restlessness
80,2,2022,False,51,17:41:00,13.0,16,20.0,6.0,63,0.180124
81,2,2022,False,51,08:38:30,21.0,15,46.0,78.0,63,0.181125
121,3,2022,False,2,18:46:30,17.0,16,22.0,14.0,64,0.137500
122,3,2022,False,2,07:30:30,17.0,19,28.0,60.0,64,0.119128
124,3,2022,False,4,22:15:00,20.0,14,24.0,35.0,65,0.106218
...,...,...,...,...,...,...,...,...,...,...,...
5170,50,2022,False,60,08:45:30,19.0,22,37.0,97.0,62,0.093560
5190,50,2022,False,80,08:44:00,20.0,22,28.0,48.0,59,0.073239
5191,50,2022,False,80,05:36:30,19.0,21,33.0,49.0,59,0.061785
5220,50,2024,True,868,13:59:00,NaN,67,NaN,31.0,65,0.118110
5221,50,2024,True,868,08:00:30,NaN,69,NaN,56.0,65,0.064683

In [174]:
def mean_time(series):
    times = pd.to_timedelta(series.astype(str))
    mean_sec = times.dt.total_seconds().mean()
    return pd.to_datetime(mean_sec, unit='s').time()

df_sleep_score_agg = (
    df_sleep_score
    .groupby(['id', 'day_in_study'], as_index=False)
    .agg({
        'timestamp': mean_time,
        'composition_score': 'mean',
        'revitalization_score': 'mean',
        'duration_score': 'mean',
        'deep_sleep_in_minutes': 'mean',
        'resting_heart_rate': 'mean',
        'restlessness': 'mean',
        'study_interval': 'first',
        'is_weekend': 'first'
    })
)

In [175]:
check_unique(df_sleep_score_agg, "df_sleep_score_agg")

df_sleep_score_agg:  Unique, it has 0 duplicates

## Merge

In [176]:
df_sleep_merge = (
    df_sleep_score_agg
    .merge(df_respiratory_modified, on=["id", "day_in_study"], how="left", suffixes=("", "_resp"))
    .merge(df_sleep_agg, on=["id", "day_in_study"], how="left", suffixes=("", "_sleep"))
   # .merge(df_oxygen_modified, on=["id", "day_in_study"], how="left", suffixes=("", "_oxy"))
   # .merge(df_wrist_temp_modified, on=["id", "day_in_study"], how="left", suffixes=("", "_wrist"))
    .merge(df_computed_temp, on=["id", "day_in_study"], how="left", suffixes=("", "_comp"))
)

In [177]:
df_sleep_merge.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5078 entries, 0 to 5077
Data columns (total 36 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   id                               5078 non-null   int64
 1   day_in_study                     5078 non-null   int64
 2   timestamp                        5078 non-null   object
 3   composition_score                3566 non-null   float64
 4   revitalization_score             5078 non-null   float64
 5   duration_score                   3566 non-null   float64
 6   deep_sleep_in_minutes            5077 non-null   float64
 7   resting_heart_rate               5078 non-null   float64
 8   restlessness                     5078 non-null   float64
 9   study_interval                   5078 non-null   int64
 10  is_weekend                       5078 non-null   bool
 11  study_interval_resp              2532 non-null   float64
 12  is_weekend_resp                  2532 non-null   object
 13  full_sleep_breathing_rate_max    2532 non-null   float64
 14  full_sleep_breathing_rate_min    2532 non-null   float64
 15  full_sleep_breathing_rate_mean   2532 non-null   float64
 16  deep_sleep_breathing_rate_max    2532 non-null   float64
 17  deep_sleep_breathing_rate_min    2532 non-null   float64
 18  deep_sleep_breathing_rate_mean   2532 non-null   float64
 19  light_sleep_breathing_rate_max   2532 non-null   float64
 20  light_sleep_breathing_rate_min   2532 non-null   float64
 21  light_sleep_breathing_rate_mean  2532 non-null   float64
 22  rem_sleep_breathing_rate_max     2532 non-null   float64
 23  rem_sleep_breathing_rate_min     2532 non-null   float64
 24  rem_sleep_breathing_rate_mean    2532 non-null   float64
 25  sleep_start_timestamp            5078 non-null   object
 26  sleep_end_timestamp              5078 non-null   object
 27  minutesasleep                    5078 non-null   int64
 28  minutesawake                     5078 non-null   int64
 29  timeinbed                        5078 non-null   int64
 30  study_interval_sleep             5078 non-null   int64
 31  is_weekend_sleep                 5078 non-null   bool
 32  study_interval_comp              5006 non-null   float64
 33  is_weekend_comp                  5006 non-null   float64
 34  temperature_samples              5006 non-null   float64
 35  nightly_temperature              5006 non-null   float64
dtypes: bool(2), float64(23), int64(7), object(4)
memory usage: 1.3+ MB

In [178]:
df_sleep_merge.drop_duplicates(inplace=True)

In [179]:
check_unique(df_sleep_merge, "df_sleep_merge")

df_sleep_merge:  Unique, it has 0 duplicates

In [180]:
df_sleep_merge.to_csv("df_sleep_merge.csv", index=False)